name: D:\jiuye\environments\lora_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - datasets==4.2.0
      - dill==0.4.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.2
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.17.1
      - pillow==11.3.0
      - propcache==0.4.1
      - psutil==7.1.1
      - pyarrow==21.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - safetensors==0.6.2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - tokenizers==0.22.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: D:\jiuye\environments\lora_env
