name: D:\jiuye\environments\agent_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - brotli==1.1.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - ddgs==9.6.1
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - frozenlist==1.8.0
      - greenlet==3.2.4
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.11
      - jiter==0.11.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.1.0
      - langchain-community==0.0.20
      - langchain-core==0.1.23
      - langchain-openai==0.0.6
      - langsmith==0.0.87
      - lxml==6.0.2
      - marshmallow==3.26.1
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - numpy==1.26.4
      - openai==1.109.1
      - packaging==23.2
      - primp==0.15.0
      - propcache==0.4.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - sniffio==1.3.1
      - socksio==1.0.0
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - tenacity==8.5.0
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - wikipedia==1.4.0
      - wikipedia-api==0.8.1
      - yarl==1.22.0
prefix: D:\jiuye\environments\agent_env
